import = [
  "~/.config/alacritty/catppuccin-macchiato.toml",
]

[font]
normal = { family = "GeistMono Nerd Font", style = "Regular"}
size = 9.0

[window]
opacity = 0.7
decorations = "Full"

[selection]
save_to_clipboard = true

[cursor.style]
shape = "Block"

[mouse]
hide_when_typing = true
