[colors.primary]
background = "#24273a"
foreground = "#cdd6f4"
dim_foreground = "#7f849c"
bright_foreground = "#cdd6f4"

[colors.cursor]
text = "#181926"
cursor = "#f4dbd6"

# [colors.vi_mode_cursor]
# text = "#cad3f5"
# cursor = "#b4befe"

[colors.search.matches]
foreground = "#cad3f5"
background = "#a6adc8"

[colors.search.focused_match]
foreground = "#cad3f5"
background = "#a6da95"

[colors.footer_bar]
foreground = "#cad3f5"
background = "#a6adc8"

[colors.hints.start]
foreground = "#cad3f5"
background = "#eed49f"

[colors.hints.end]
foreground = "#cad3f5"
background = "#a6adc8"

[colors.selection]
text = "#cad3f5"
background = "#f5e0dc"

[colors.normal]
black = "#45475a"
red = "#ed8796"
green = "#a6da95"
yellow = "#eed49f"
blue = "#8aadf4"
magenta = "#f5c2e7"
cyan = "#94e2d5"
white = "#bac2de"

[colors.bright]
black = "#585b70"
red = "#ed8796"
green = "#a6da95"
yellow = "#eed49f"
blue = "#8aadf4"
magenta = "#f5c2e7"
cyan = "#94e2d5"
white = "#a6adc8"

[colors.dim]
black = "#45475a"
red = "#ed8796"
green = "#a6da95"
yellow = "#eed49f"
blue = "#8aadf4"
magenta = "#f5c2e7"
cyan = "#94e2d5"
white = "#bac2de"

[[colors.indexed_colors]]
index = 16
color = "#fab387"

[[colors.indexed_colors]]
index = 17
color = "#f5e0dc"
